// Generated by Sumi. Keeps WebKit-hosted extension runtime manifests Safari-compatible.
(function () {
  'use strict';

  var root = typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : this);
  var marker = '__sumiWebKitRuntimeCompatibilityPreludeInstalled';
  if (!root) return;

  try {
    Object.defineProperty(root, marker, { value: true, configurable: false });
  } catch (_) {
    root[marker] = true;
  }

  var browserSpecificSettings = __SUMI_BROWSER_SPECIFIC_SETTINGS_JSON__;

  function cloneValue(value) {
    if (!value || typeof value !== 'object') return value;
    if (Array.isArray(value)) return value.map(cloneValue);
    var output = {};
    Object.keys(value).forEach(function (key) {
      output[key] = cloneValue(value[key]);
    });
    return output;
  }

  if (!browserSpecificSettings || typeof browserSpecificSettings !== 'object') return;

  function patchRuntimeGetManifest(runtime) {
    if (!runtime || typeof runtime.getManifest !== 'function') return;
    if (runtime.getManifest.__sumiWebKitRuntimeCompatibilityWrapped) return;

    var originalGetManifest = runtime.getManifest;
    var wrappedGetManifest = function () {
      var manifest = originalGetManifest.apply(runtime, arguments);
      if (!manifest || typeof manifest !== 'object') return manifest;
      if (manifest.browser_specific_settings) return manifest;

      var patchedManifest = cloneValue(manifest);
      patchedManifest.browser_specific_settings = cloneValue(browserSpecificSettings);
      return patchedManifest;
    };

    try {
      Object.defineProperty(wrappedGetManifest, '__sumiWebKitRuntimeCompatibilityWrapped', {
        value: true,
        configurable: false
      });
    } catch (_) {}

    try {
      runtime.getManifest = wrappedGetManifest;
    } catch (_) {
      try {
        Object.defineProperty(runtime, 'getManifest', {
          value: wrappedGetManifest,
          configurable: true,
          writable: true
        });
      } catch (_) {}
    }
  }

  function suppressUnsupportedMethod(target, methodName) {
    if (!target || typeof target !== 'object') return;

    try {
      delete target[methodName];
    } catch (_) {}

    try {
      target[methodName] = undefined;
    } catch (_) {}

    try {
      Object.defineProperty(target, methodName, {
        configurable: true,
        enumerable: false,
        get: function () {
          return undefined;
        },
        set: function () {}
      });
    } catch (_) {}
  }

  function patchUnsupportedMethodGroup(apiRoot, propertyName, methodNames) {
    var target;
    try {
      target = apiRoot && apiRoot[propertyName];
    } catch (_) {
      target = undefined;
    }

    if (!target || typeof target !== 'object') return;

    methodNames.forEach(function (methodName) {
      suppressUnsupportedMethod(target, methodName);
    });
  }

  function installApiMemberAccessor(apiRoot, propertyName, patcher) {
    if (!apiRoot || typeof apiRoot !== 'object') return;

    var watchMarker = '__sumiWebKitRuntimeCompatibilityMemberWatched_' + propertyName;
    if (apiRoot[watchMarker]) {
      patcher(apiRoot);
      return;
    }

    var descriptor;
    try {
      descriptor = Object.getOwnPropertyDescriptor(apiRoot, propertyName);
    } catch (_) {
      descriptor = null;
    }

    if (descriptor && descriptor.configurable === false) {
      patcher(apiRoot);
      return;
    }

    var currentValue;
    var originalGetter = descriptor && descriptor.get;
    var originalSetter = descriptor && descriptor.set;
    if (originalGetter) {
      try {
        currentValue = originalGetter.call(apiRoot);
      } catch (_) {
        currentValue = undefined;
      }
    } else if (descriptor && Object.prototype.hasOwnProperty.call(descriptor, 'value')) {
      currentValue = descriptor.value;
    } else {
      currentValue = apiRoot[propertyName];
    }

    patcher(apiRoot);

    try {
      Object.defineProperty(apiRoot, propertyName, {
        configurable: true,
        enumerable: descriptor ? descriptor.enumerable : true,
        get: function () {
          if (originalGetter) {
            try {
              return originalGetter.call(apiRoot);
            } catch (_) {
              return currentValue;
            }
          }
          return currentValue;
        },
        set: function (value) {
          if (originalSetter) {
            try {
              originalSetter.call(apiRoot, value);
            } catch (_) {}
          } else {
            currentValue = value;
          }
          patcher(apiRoot);
        }
      });
      try {
        Object.defineProperty(apiRoot, watchMarker, {
          value: true,
          configurable: false
        });
      } catch (_) {
        apiRoot[watchMarker] = true;
      }
    } catch (_) {}
  }

  function patchUnsupportedProgrammaticContentScriptAPIs(apiRoot) {
    if (!apiRoot || typeof apiRoot !== 'object') return;

    patchUnsupportedMethodGroup(apiRoot, 'contentScripts', ['register']);
    patchUnsupportedMethodGroup(apiRoot, 'scripting', ['registerContentScripts', 'executeScript', 'insertCSS']);
    patchUnsupportedMethodGroup(apiRoot, 'tabs', ['executeScript', 'insertCSS']);
    installApiMemberAccessor(apiRoot, 'contentScripts', function (target) {
      patchUnsupportedMethodGroup(target, 'contentScripts', ['register']);
    });
    installApiMemberAccessor(apiRoot, 'scripting', function (target) {
      patchUnsupportedMethodGroup(target, 'scripting', ['registerContentScripts', 'executeScript', 'insertCSS']);
    });
    installApiMemberAccessor(apiRoot, 'tabs', function (target) {
      patchUnsupportedMethodGroup(target, 'tabs', ['executeScript', 'insertCSS']);
    });
  }

  function installRuntimeAccessor(apiRoot) {
    if (!apiRoot || typeof apiRoot !== 'object') return;
    if (apiRoot.__sumiWebKitRuntimeCompatibilityRuntimeWatched) return;

    try {
      Object.defineProperty(apiRoot, '__sumiWebKitRuntimeCompatibilityRuntimeWatched', {
        value: true,
        configurable: false
      });
    } catch (_) {}

    var descriptor;
    try {
      descriptor = Object.getOwnPropertyDescriptor(apiRoot, 'runtime');
    } catch (_) {
      descriptor = null;
    }

    if (descriptor && descriptor.configurable === false) return;

    var currentRuntime;
    var originalGetter = descriptor && descriptor.get;
    var originalSetter = descriptor && descriptor.set;
    if (originalGetter) {
      try {
        currentRuntime = originalGetter.call(apiRoot);
      } catch (_) {
        currentRuntime = undefined;
      }
    } else if (descriptor && Object.prototype.hasOwnProperty.call(descriptor, 'value')) {
      currentRuntime = descriptor.value;
    } else {
      currentRuntime = apiRoot.runtime;
    }

    try {
      Object.defineProperty(apiRoot, 'runtime', {
        configurable: true,
        enumerable: descriptor ? descriptor.enumerable : true,
        get: function () {
          if (originalGetter) {
            try {
              return originalGetter.call(apiRoot);
            } catch (_) {
              return currentRuntime;
            }
          }
          return currentRuntime;
        },
        set: function (value) {
          if (originalSetter) {
            try {
              originalSetter.call(apiRoot, value);
            } catch (_) {}
          } else {
            currentRuntime = value;
          }
          patchRuntimeGetManifest(value);
        }
      });
    } catch (_) {}
  }

  function patchApiRoot(apiRoot) {
    if (!apiRoot || typeof apiRoot !== 'object') return;
    patchRuntimeGetManifest(apiRoot.runtime);
    patchUnsupportedProgrammaticContentScriptAPIs(apiRoot);
    installRuntimeAccessor(apiRoot);
  }

  function installApiRootAccessor(propertyName) {
    var watchMarker = '__sumiWebKitRuntimeCompatibility' + propertyName + 'Watched';
    if (root[watchMarker]) {
      patchApiRoot(root[propertyName]);
      return;
    }

    var descriptor;
    try {
      descriptor = Object.getOwnPropertyDescriptor(root, propertyName);
    } catch (_) {
      descriptor = null;
    }

    if (descriptor && descriptor.configurable === false) {
      patchApiRoot(root[propertyName]);
      return;
    }

    var currentApiRoot;
    var originalGetter = descriptor && descriptor.get;
    var originalSetter = descriptor && descriptor.set;
    if (originalGetter) {
      try {
        currentApiRoot = originalGetter.call(root);
      } catch (_) {
        currentApiRoot = undefined;
      }
    } else if (descriptor && Object.prototype.hasOwnProperty.call(descriptor, 'value')) {
      currentApiRoot = descriptor.value;
    } else {
      currentApiRoot = root[propertyName];
    }

    patchApiRoot(currentApiRoot);

    try {
      Object.defineProperty(root, propertyName, {
        configurable: true,
        enumerable: descriptor ? descriptor.enumerable : true,
        get: function () {
          if (originalGetter) {
            try {
              return originalGetter.call(root);
            } catch (_) {
              return currentApiRoot;
            }
          }
          return currentApiRoot;
        },
        set: function (value) {
          if (originalSetter) {
            try {
              originalSetter.call(root, value);
            } catch (_) {}
          } else {
            currentApiRoot = value;
          }
          patchApiRoot(value);
        }
      });
      try {
        Object.defineProperty(root, watchMarker, {
          value: true,
          configurable: false
        });
      } catch (_) {
        root[watchMarker] = true;
      }
    } catch (_) {}
  }

  installApiRootAccessor('chrome');
  installApiRootAccessor('browser');
})();
