// DuckDuckGo URL Predictor - C ABI
// This header is auto-generated by cbindgen. Do not edit by hand.


#ifndef DDG_URL_PREDICTOR_H
#define DDG_URL_PREDICTOR_H

#pragma once

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Classify an input string (URL-ish or search) using a JSON-encoded `Policy`.
 *
 * # Parameters
 * - `input`: UTF-8 C string (NUL-terminated).
 * - `policy_json`: UTF-8 C string with a JSON object for `Policy`.
 *
 * # Returns
 * A newly allocated UTF-8 JSON C string with a `Decision`.
 * Must be freed with [`ddg_up_free_string`].
 *
 * # Safety
 * - `input` and `policy_json` must be valid pointers to NUL-terminated byte strings.
 * - The returned pointer must be freed only via [`ddg_up_free_string`].
 */
char *ddg_up_classify_json(const char *input, const char *policy_json);

/**
 * Free a string returned by this library (e.g., from [`ddg_up_classify_json`]).
 *
 * Safe to call with NULL; it will do nothing.
 *
 * # Safety
 * - `ptr` must be a pointer previously returned by this library.
 *   Do **not** pass a pointer from `malloc`/`new`/stack.
 */
void ddg_up_free_string(char *ptr);

/**
 * Get a pointer to the in-memory Public Suffix List (PSL) bytes.
 *
 * Available only when built with the `real-psl` feature.
 *
 * The memory is **owned by the library** and is valid for the lifetime of the process.
 * Do **not** free it. The buffer is NUL-terminated for convenience.
 *
 * Use together with [`ddg_up_get_psl_len`] to know the logical length (without the trailing NUL).
 *
 * # Returns
 * `*const c_char` pointing to a read-only, NUL-terminated buffer.
 */
const char *ddg_up_get_psl_ptr(void);

/**
 * Get the length (in bytes) of the PSL buffer returned by [`ddg_up_get_psl_ptr`].
 *
 * The length **excludes** the trailing NUL.
 *
 * # Returns
 * `usize` length in bytes.
 */
uintptr_t ddg_up_get_psl_len(void);

#endif  /* DDG_URL_PREDICTOR_H */
