import Foundation

enum SumiPermissionRuntimeControlsStrings {
    static let defaultDisplayDomain = "This site"
    static let sectionTitle = "Active now"
    static let cameraTitle = "Camera"
    static let microphoneTitle = "Microphone"
    static let locationTitle = "Location"
    static let screenSharingTitle = "Screen sharing"
    static let autoplayTitle = "Autoplay"

    static let cameraActive = "Camera is active on this page"
    static let cameraMuted = "Camera is muted on this page"
    static let microphoneActive = "Microphone is active on this page"
    static let microphoneMuted = "Microphone is muted on this page"
    static let locationActive = "Location sharing is active"
    static let locationPaused = "Location sharing is paused"
    static let screenSharingControlledByWebKit = "Screen sharing is controlled by the site/WebKit picker"
    static let autoplayReloadRequired = "Reload to apply the autoplay setting"
    static let stopping = "Stopping"
    static let revoking = "Stopping"

    static let muteCamera = "Mute camera"
    static let unmuteCamera = "Unmute camera"
    static let stopCamera = "Stop camera access for this page"
    static let muteMicrophone = "Mute microphone"
    static let unmuteMicrophone = "Unmute microphone"
    static let stopMicrophone = "Stop microphone access for this page"
    static let pauseLocation = "Pause location sharing"
    static let resumeLocation = "Resume location sharing"
    static let stopLocationThisVisit = "Stop sharing location this visit"
    static let reloadAutoplay = "Reload to apply autoplay setting"

    static let stopCameraAccessibility = "Stop camera access for this page"
    static let stopMicrophoneAccessibility = "Stop microphone access for this page"
    static let pauseLocationAccessibility = "Pause location sharing"
    static let resumeLocationAccessibility = "Resume location sharing"
    static let stopLocationAccessibility = "Stop sharing location this visit"
    static let reloadAutoplayAccessibility = "Reload to apply autoplay setting"

    static let alreadyCurrent = "Already up to date"
    static let cameraMutedResult = "Camera muted"
    static let cameraUnmutedResult = "Camera unmuted"
    static let cameraStoppedResult = "Camera stopped for this page"
    static let microphoneMutedResult = "Microphone muted"
    static let microphoneUnmutedResult = "Microphone unmuted"
    static let microphoneStoppedResult = "Microphone stopped for this page"
    static let locationPausedResult = "Location sharing paused"
    static let locationResumedResult = "Location sharing resumed"
    static let locationStoppedResult = "Location sharing stopped for this visit"
    static let autoplayReloadingResult = "Reloading page"
    static let unavailableInWebKit = "This control is unavailable in WebKit"
    static let noCurrentPage = "No current page is available"
    static let pageChanged = "The page changed. Refreshing controls."
    static let locationNoLongerAllowed = "Location permission is no longer allowed for this page"
    static let updateFailed = "Could not update this permission"
}
