#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

checks=(
  "scripts/check_architecture_guard_dsl.sh"
  "scripts/check_architecture_tombstones.sh"
  "scripts/check_adblock_update_architecture.sh"
  "scripts/check_protection_architecture.sh"
  "scripts/check_protected_command_dispatch_boundary.sh"
  "scripts/check_auxiliary_window_architecture.sh"
  "scripts/check_extension_browser_bridge_architecture.sh"
  "scripts/check_extension_normal_tab_runtime_boundary.sh"
  "scripts/check_extension_controller_runtime_boundary.sh"
  "scripts/check_extension_runtime_lifecycle_boundary.sh"
  "scripts/check_extension_context_load_boundary.sh"
  "scripts/check_extension_permission_policy_boundary.sh"
  "scripts/check_extension_installation_transaction_boundary.sh"
  "scripts/check_installed_extension_catalog_boundary.sh"
  "scripts/check_extension_settings_scan_session_boundary.sh"
  "scripts/check_extension_runtime_retirement_boundary.sh"
  "scripts/check_extension_requested_window_transaction.sh"
  "scripts/check_extension_permission_callback_admission.sh"
  "scripts/check_extension_native_messaging_callback_admission.sh"
  "scripts/check_extension_action_invocation_admission.sh"
  "scripts/check_extension_action_popup_lifecycle_boundary.sh"
  "scripts/check_extension_options_window_lifetime.sh"
  "scripts/check_extension_utility_roles.sh"
  "scripts/check_extension_auxiliary_roles.sh"
  "scripts/check_ddg_vendor_test_boundary.sh"
  "scripts/check_modernization_debt.sh"
  "scripts/check_di_ceremony_debt.sh"
  "scripts/check_domain_isolation_boundary.sh"
  "scripts/check_workspace_theme_architecture.sh"
  "scripts/check_download_architecture.sh"
  "scripts/check_webruntime_isolation_boundary.sh"
  "scripts/check_import_export_boundaries.sh"
  "scripts/check_bookmark_import_dto_boundary.sh"
  "scripts/check_bookmark_publication_boundary.sh"
  "scripts/check_prepared_bundle_runtime_boundary.sh"
  "scripts/check_safari_extension_clean_import.sh"
  "scripts/check_settings_browser_manager_boundary.sh"
  "scripts/check_general_settings_boundaries.sh"
  "scripts/check_sidebar_browser_manager_boundary.sh"
  "scripts/check_sidebar_drop_coordinator_boundary.sh"
  "scripts/check_tab_closure_service_boundary.sh"
  "scripts/check_tab_webview_ownership_boundary.sh"
  "scripts/check_tab_configuration_policy_architecture.sh"
  "scripts/check_webview_interaction_state_boundary.sh"
  "scripts/check_popup_navigation_architecture.sh"
  "scripts/check_tab_suspension_architecture.sh"
  "scripts/check_background_media_lifecycle_boundary.sh"
  "scripts/check_tab_persistence_architecture.sh"
  "scripts/check_favicon_production_ownership.sh"
  "scripts/check_window_registration_transaction.sh"
  "scripts/check_split_architecture.sh"
  "scripts/check_startup_persistence_boundary.sh"
  "scripts/check_persistence_inventory.sh"
  "scripts/check_tracker_radar_import_boundary.sh"
  "scripts/check_updater_sparkle_boundary.sh"
  "scripts/check_website_compositor_boundaries.sh"
  "scripts/check_website_data_mutation_boundary.sh"
  "scripts/check_webview_runtime_context_boundary.sh"
  "scripts/check_gpc_navigation_fail_closed.sh"
  "scripts/check_architecture_structural_metrics.sh"
  "scripts/check_architecture_structural_boundaries.sh"
  "scripts/check_no_tab_manager_runtime_context.sh"
  "scripts/check_history_tab_recorder_location.sh"
  "scripts/check_sidebar_chrome_folder_boundary.sh"
  "scripts/check_sidebar_view_coupling.sh"
  "scripts/check_sidebar_observation_boundary.sh"
  "scripts/check_space_view_decomposition.sh"
  "scripts/check_no_exported_domain_webruntime.sh"
  "scripts/check_package_topology.sh"
  "scripts/check_test_file_loc.sh"
  "scripts/check_ui_test_fixture_boundary.sh"
  "scripts/check_localization_accessibility_boundary.sh"
)

for check in "${checks[@]}"; do
  echo "==> ${check}"
  "${check}"
done

echo "==> scripts/check_browser_script_hot_paths.sh"
bash scripts/check_browser_script_hot_paths.sh

echo "==> scripts/check_removed_userscript_product.sh"
bash scripts/check_removed_userscript_product.sh

echo "architecture guardrails passed"
